

spring:
  application:
    name:dineInOrderAPI:

  datasource:
    url:jdbc:mysql://localhost:3306/dineIn?createDatabaseIfNotExist=true
    username:root
    password:root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:update



